module OctaveCall

# this needs to be set globally for Cxx to work with liboctave,
# unfortunately (and possibly requirex Cxx to be re-built):
ENV["JULIA_CXX_RTTI"]=1

using Cxx
import Libdl

const depfile = joinpath(dirname(@__FILE__), "..", "deps", "deps.jl")
isfile(depfile) || error("OctaveCall not properly installed. Please run Pkg.build(\"IJulia\")")
include(depfile) # generated by Pkg.build("OctaveCall")

function __init__()
    addHeaderDir(dirname(oct_h), kind=C_User)
    Libdl.dlopen(liboctave, Libdl.RTLD_GLOBAL)
    cxxinclude(basename(oct_h))
end

include("oct2jl.jl")
include("jl2oct.jl")

end # module
