module OctCall

export jl2oct, oct2jl

using Cxx
import Libdl

const depfile = joinpath(dirname(@__FILE__), "..", "deps", "deps.jl")
isfile(depfile) || error("OctCall not properly installed. Please run Pkg.build(\"IJulia\")")
include(depfile) # generated by Pkg.build("OctCall")

cxx"""
#include <complex>
"""

if oct_h_dir !== nothing
    addHeaderDir(oct_h_dir, kind=C_System)
end
cxxinclude("oct.h")
cxxinclude("interpreter.h")

function __init__()
    Libdl.dlopen(liboctave, Libdl.RTLD_GLOBAL)
    Libdl.dlopen(liboctinterp, Libdl.RTLD_GLOBAL)
    if oct_h_dir !== nothing
        addHeaderDir(oct_h_dir, kind=C_System)
    end
    cxxinclude("oct.h")
    cxxinclude("interpreter.h")
end

include("conversions.jl")
include("ov-conversions.jl")
include("interpreter.jl")

end # module
