module OctCall

export jl2oct, oct2jl

using Cxx
import Libdl

const depfile = joinpath(dirname(@__FILE__), "..", "deps", "deps.jl")
isfile(depfile) || error("OctCall not properly installed. Please run Pkg.build(\"IJulia\")")
include(depfile) # generated by Pkg.build("OctCall")

cxx"""
#include <complex>
"""

addHeaderDir(dirname(oct_h), kind=C_User)
cxxinclude(basename(oct_h))

function __init__()
    Libdl.dlopen(liboctave, Libdl.RTLD_GLOBAL)
    addHeaderDir(dirname(oct_h), kind=C_User)
    cxxinclude(basename(oct_h))
end

include("conversions.jl")

end # module
